name: Bongkar Google Env

on:
  workflow_dispatch: # Memunculkan tombol untuk menjalankan manual

jobs:
  tampilkan-key:
    runs-on: ubuntu-latest
    steps:
      - name: Ekstrak dan Pisah Karakter
        run: |
          CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}"
          CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}"
          
          echo "=================================================="
          echo "GOOGLE_CLIENT_ID Anda (baca tanpa spasi):"
          echo "$CLIENT_ID" | sed 's/./& /g'
          
          echo "=================================================="
          echo "GOOGLE_CLIENT_SECRET Anda (baca tanpa spasi):"
          echo "$CLIENT_SECRET" | sed 's/./& /g'
          echo "=================================================="
